version: '3.9'
services:
  frontend:
    build: 
      context: ./frontend
    image: "node:10-alpine"
    container_name: postboy_frontend
    ports:
      - '3000:3000'
    volumes:
     - ./frontend:/postboy/frontend
    depends_on:
      - backend
  backend:
    container_name: postboy_backend
    build: 
      context: ./backend
    depends_on:
      - postgres
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/postboy/backend
  postgres:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
  redis:
    image: redis:latest
volumes:
  pgdata:
    external: true
