FROM ruby:3.0.2
RUN apt-get update -qq && apt-get install -y postgresql-client
RUN mkdir -p /postboy/backend
WORKDIR /postboy/backend
COPY ./Gemfile* ./
RUN bundle install
COPY ./ ./

# Add a script to be executed every time the container starts.
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 3001

# Start the main process.
CMD ["rails", "server", "-b", "0.0.0.0"]
